---
title: "Homework 2"
author: "Alisa Hartle"
date: "October 2, 2019"
output: html_document
---


  
```{r setup, include=FALSE}
require(rgdal)
require(leaflet)
require(leaflet.extras)
require(leaflet.providers)
require(readit)

require(dplyr)
require(readxl)
require(stringr)
```

# Loading in the data

```{r}

#All datasets brought to you by NYCOpenData

#neighborhood tabulation areas
n_tabs <- readOGR("Neighborhood Tabulation Areas.geojson")

# MTA subway stations
stations <- readOGR("Subway Stations.geojson")


# MTA subway lines
lines <- readOGR("Subway Lines.geojson")

# Population counts for each neighborhood tabulation area
pop <- readit('demo_2016acs5yr_nta.xlsx')
```

# Creating a base map that will be used later

```{r, controls}

base <-leaflet() %>%
  setView(lat = 40.75, lng = -74, zoom = 11.3) 

base <- base %>%
  addProviderTiles(providers$Stamen.TonerBackground)


```


# A map of Neighborhood Tabulation Areas in NYC
```{r, polygon}


leaflet(data = n_tabs) %>%
  setView(lat = 40.75, lng = -73.9, zoom = 11.3) %>%
  addProviderTiles(providers$Stamen.TonerBackground) %>%
  addPolygons(color = '#2ca25f', weight = 2)


```


# Point Maps with the NYC Subway
```{r}


points <- leaflet(data = stations) %>%
  setView(lat = 40.75, lng = -74, zoom = 11.3) %>%
  addTiles() %>%
  addProviderTiles(providers$Stamen.TonerBackground) %>%
  addCircleMarkers(radius = 1, color = '#18567d', opacity = 1)

points
```

# Plotting subway lines. And if you think I'm bad at picking 
# a basemap, you can pick a different one.

```{r}


leaflet(data = lines) %>%
  setView(lat = 40.75, lng = -73.9, zoom = 11.3) %>%
  addTiles() %>%
  addProviderTiles(providers$Stamen.TonerBackground) %>%
  addProviderTiles("Stamen.TonerLite", group = "Toner Lite") %>%
  addPolylines() %>%
  addLayersControl(
    baseGroups = c("Toner", "Toner Lite"),
    options = layersControlOptions(collapsed = FALSE))

 

```

#Incorporating population data

```{r}

merge_things <- merge(x = n_tabs, y = pop, by.x = "ntacode", by.y = "GeoID")
bins <- c(0, 30000, 35000, 40000, 45000, 50000, 550000, 60000, Inf)
pal <- colorBin("OrRd", domain = merge_things$Pop_1E, bins = bins)


base %>%
  addPolygons(data = merge_things, color = '#7d2218', fillColor = ~pal(Pop_1E), 
              fillOpacity = 1, weight = 2) %>%
  addLegend(pal = pal, values = merge_things$Pop_1E,
            opacity = 1.0, title = 'Population Totals',
            position = "bottomleft")


```


